import { Zap, TrendingUp, Shield, Battery, Lightbulb, SkipForward, Sparkles, Palette, Award, Star, Lock, Crown, MessageSquare, GraduationCap } from 'lucide-react';

export type ShopItemCategory = 'power-ups' | 'cosmetics' | 'exclusive-content' | 'status-symbols';
export type ShopItemType = 'consumable' | 'permanent';

export interface ShopItem {
  id: string;
  name: string;
  description: string;
  category: ShopItemCategory;
  type: ShopItemType;
  price: number;
  icon: any;
  iconColor: string;
  duration?: number; // in minutes for consumables
  effect?: string;
  rarity: 'common' | 'rare' | 'epic' | 'legendary';
}

export const SHOP_CATALOG: ShopItem[] = [
  // Power-Ups (Consumables)
  {
    id: 'xp-boost-2x',
    name: '2x XP Boost',
    description: 'Double all XP earned for 1 hour',
    category: 'power-ups',
    type: 'consumable',
    price: 250,
    icon: Zap,
    iconColor: 'text-yellow-500',
    duration: 60,
    effect: 'multiplier_xp_2x',
    rarity: 'rare',
  },
  {
    id: 'coin-multiplier-3x',
    name: '3x Coin Multiplier',
    description: 'Triple coin conversion rate for 1 hour',
    category: 'power-ups',
    type: 'consumable',
    price: 400,
    icon: TrendingUp,
    iconColor: 'text-green-500',
    duration: 60,
    effect: 'multiplier_coins_3x',
    rarity: 'epic',
  },
  {
    id: 'streak-shield',
    name: 'Streak Shield',
    description: 'Protect your streak from breaking once',
    category: 'power-ups',
    type: 'consumable',
    price: 300,
    icon: Shield,
    iconColor: 'text-blue-500',
    effect: 'streak_protection',
    rarity: 'rare',
  },
  {
    id: 'energy-refill',
    name: 'Energy Refill',
    description: 'Restore energy for Bamboo Empire Game',
    category: 'power-ups',
    type: 'consumable',
    price: 100,
    icon: Battery,
    iconColor: 'text-orange-500',
    effect: 'refill_energy',
    rarity: 'common',
  },
  {
    id: 'hint-tokens',
    name: 'Hint Tokens (5x)',
    description: 'Get hints on difficult flashcards',
    category: 'power-ups',
    type: 'consumable',
    price: 150,
    icon: Lightbulb,
    iconColor: 'text-purple-500',
    effect: 'hint_tokens_5',
    rarity: 'common',
  },
  {
    id: 'skip-card',
    name: 'Skip Card',
    description: 'Skip a difficult flashcard without penalty',
    category: 'power-ups',
    type: 'consumable',
    price: 50,
    icon: SkipForward,
    iconColor: 'text-cyan-500',
    effect: 'skip_flashcard',
    rarity: 'common',
  },

  // Cosmetics (Permanent)
  {
    id: 'panda-classic',
    name: 'Classic Panda Avatar',
    description: 'Traditional black and white panda',
    category: 'cosmetics',
    type: 'permanent',
    price: 500,
    icon: Sparkles,
    iconColor: 'text-slate-700',
    effect: 'avatar_panda_classic',
    rarity: 'common',
  },
  {
    id: 'panda-golden',
    name: 'Golden Panda Avatar',
    description: 'Rare golden panda skin',
    category: 'cosmetics',
    type: 'permanent',
    price: 1200,
    icon: Sparkles,
    iconColor: 'text-yellow-600',
    effect: 'avatar_panda_golden',
    rarity: 'epic',
  },
  {
    id: 'panda-rainbow',
    name: 'Rainbow Panda Avatar',
    description: 'Legendary rainbow panda skin',
    category: 'cosmetics',
    type: 'permanent',
    price: 3000,
    icon: Sparkles,
    iconColor: 'text-pink-500',
    effect: 'avatar_panda_rainbow',
    rarity: 'legendary',
  },
  {
    id: 'card-theme-dark',
    name: 'Dark Mode Card Theme',
    description: 'Sleek dark flashcard design',
    category: 'cosmetics',
    type: 'permanent',
    price: 300,
    icon: Palette,
    iconColor: 'text-slate-900',
    effect: 'card_theme_dark',
    rarity: 'common',
  },
  {
    id: 'card-theme-neon',
    name: 'Neon Card Theme',
    description: 'Vibrant neon flashcard design',
    category: 'cosmetics',
    type: 'permanent',
    price: 600,
    icon: Palette,
    iconColor: 'text-purple-500',
    effect: 'card_theme_neon',
    rarity: 'rare',
  },
  {
    id: 'badge-scholar',
    name: 'Scholar Badge',
    description: 'Display your dedication to learning',
    category: 'cosmetics',
    type: 'permanent',
    price: 200,
    icon: Award,
    iconColor: 'text-blue-600',
    effect: 'badge_scholar',
    rarity: 'common',
  },
  {
    id: 'badge-master',
    name: 'Master Badge',
    description: 'Show your expertise',
    category: 'cosmetics',
    type: 'permanent',
    price: 800,
    icon: Star,
    iconColor: 'text-amber-600',
    effect: 'badge_master',
    rarity: 'epic',
  },

  // Exclusive Content
  {
    id: 'unlock-pro-flashcards',
    name: 'Unlock Pro Flashcards Early',
    description: 'Access advanced flashcard deck immediately',
    category: 'exclusive-content',
    type: 'permanent',
    price: 800,
    icon: Lock,
    iconColor: 'text-red-600',
    effect: 'unlock_pro_flashcards',
    rarity: 'rare',
  },
  {
    id: 'expert-interview-1',
    name: 'Expert Interview: Investment Banking',
    description: 'Exclusive video interview with IB professional',
    category: 'exclusive-content',
    type: 'permanent',
    price: 600,
    icon: MessageSquare,
    iconColor: 'text-indigo-600',
    effect: 'video_ib_interview',
    rarity: 'rare',
  },
  {
    id: 'case-study-premium',
    name: 'Premium Case Studies (3x)',
    description: 'In-depth analysis of real finance cases',
    category: 'exclusive-content',
    type: 'permanent',
    price: 750,
    icon: GraduationCap,
    iconColor: 'text-emerald-600',
    effect: 'case_studies_premium',
    rarity: 'epic',
  },
  {
    id: 'private-coaching',
    name: 'Private Coach Session',
    description: '30-minute 1-on-1 mentoring session',
    category: 'exclusive-content',
    type: 'permanent',
    price: 2500,
    icon: Star,
    iconColor: 'text-purple-700',
    effect: 'private_coaching',
    rarity: 'legendary',
  },

  // Status Symbols
  {
    id: 'vip-badge-7d',
    name: 'VIP Badge (7 Days)',
    description: 'Exclusive VIP status for one week',
    category: 'status-symbols',
    type: 'consumable',
    price: 1000,
    icon: Crown,
    iconColor: 'text-yellow-500',
    duration: 10080, // 7 days in minutes
    effect: 'vip_status_7d',
    rarity: 'epic',
  },
  {
    id: 'leaderboard-highlight-7d',
    name: 'Leaderboard Highlight (7 Days)',
    description: 'Stand out on the leaderboard',
    category: 'status-symbols',
    type: 'consumable',
    price: 500,
    icon: Star,
    iconColor: 'text-amber-500',
    duration: 10080,
    effect: 'leaderboard_highlight_7d',
    rarity: 'rare',
  },
  {
    id: 'custom-title',
    name: 'Custom Title',
    description: 'Create your own profile title',
    category: 'status-symbols',
    type: 'permanent',
    price: 1500,
    icon: Award,
    iconColor: 'text-pink-600',
    effect: 'custom_title',
    rarity: 'epic',
  },
  {
    id: 'profile-frame',
    name: 'Golden Profile Frame',
    description: 'Premium border for your profile',
    category: 'status-symbols',
    type: 'permanent',
    price: 800,
    icon: Sparkles,
    iconColor: 'text-yellow-600',
    effect: 'profile_frame_golden',
    rarity: 'rare',
  },
];

export const CATEGORY_INFO = {
  'power-ups': {
    name: 'Power-Ups',
    description: 'Boost your learning with temporary enhancements',
    color: 'text-yellow-600',
    bgColor: 'bg-yellow-50 dark:bg-yellow-950/20',
    borderColor: 'border-yellow-300',
  },
  'cosmetics': {
    name: 'Cosmetics',
    description: 'Customize your learning experience',
    color: 'text-purple-600',
    bgColor: 'bg-purple-50 dark:bg-purple-950/20',
    borderColor: 'border-purple-300',
  },
  'exclusive-content': {
    name: 'Exclusive Content',
    description: 'Premium learning materials and resources',
    color: 'text-emerald-600',
    bgColor: 'bg-emerald-50 dark:bg-emerald-950/20',
    borderColor: 'border-emerald-300',
  },
  'status-symbols': {
    name: 'Status Symbols',
    description: 'Show off your achievements and dedication',
    color: 'text-pink-600',
    bgColor: 'bg-pink-50 dark:bg-pink-950/20',
    borderColor: 'border-pink-300',
  },
};

export const RARITY_INFO = {
  common: {
    color: 'text-slate-600',
    bgColor: 'bg-slate-100 dark:bg-slate-800',
    label: 'Common',
  },
  rare: {
    color: 'text-blue-600',
    bgColor: 'bg-blue-100 dark:bg-blue-900/30',
    label: 'Rare',
  },
  epic: {
    color: 'text-purple-600',
    bgColor: 'bg-purple-100 dark:bg-purple-900/30',
    label: 'Epic',
  },
  legendary: {
    color: 'text-amber-600',
    bgColor: 'bg-amber-100 dark:bg-amber-900/30',
    label: 'Legendary',
  },
};
